### PR TITLE
BREAKING: remove duplicate helpers & dependencies

### PR DESCRIPTION
**Pull request by nickschot**
Fixes: #51 & #58 

Look! A trick! This brings down the lodash gzipped size from ~90kB to ~15kB~ 0kB!.

~An "after" image of one of my templates' auto imported packages:~
image

### CODE REVIEW

**Comment by nickschot** [comment]
Before this can be merged we first need to land https://github.com/empress/empress-blog-ghost-helpers & updates to the default templates to use that addon.

**Comment by nickschot** [comment]
I've updated this so it only includes the `excerpt` helper which is used by empress-blog itself. All moment and unnecessary lodash stuff is now removed from dependencies.

This can be merged once:
- [ ] empress-blog-ghost-helpers has been released
- [ ] empress-blog-casper-template has been updated to use ghost-helpers & has been released

**Comment by nickschot** [comment]
Last two commits upgrade to the new empress-blog-casper-template & they replace lodash with (absolutely tiny) native code or ember util saving another 15kB gzipped over the previous version of this PR. Lodash is now not shipped at all by empress-blog itself.

**Review by mansona — APPROVED** [review]
great work 🎉

**Pull request merged**
